//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAdminLog
    {
        public int SeqNo { get; set; }
        public short MenuNo { get; set; }
        public string MenuLink { get; set; }
        public string MethodName { get; set; }
        public string LogDesc { get; set; }
        public System.DateTime LogYMD { get; set; }
        public string IPAddr { get; set; }
        public string LogHash { get; set; }
        public string AdminID { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
