//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TAdminMgmt
    {
        [Required(ErrorMessage = "Required.")]
        public string AdminID { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string AdminPwd { get; set; }

        [Required(ErrorMessage = "Confirmation Password is required.")]
        [Compare("AdminPwd", ErrorMessage = "Password and Confirmation Password must match.")]
        public string ConfirmPassword { get; set; }

        public string AdminName { get; set; }
        public short MenuRoleNo { get; set; }
        public string Dept { get; set; }
        public string Position { get; set; }
        public string OfficePhoneNo { get; set; }
        public string MPhoneNo { get; set; }

        [Required(ErrorMessage = "Required.")]
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        public string EmailAddr { get; set; }

        public byte UseLangTypeCode { get; set; }
        public string AccessIPChkFlag { get; set; }
        public string AccessIP1 { get; set; }
        public string AccessIP2 { get; set; }
        public string AccessIP3 { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> PwdUpdDate { get; set; }
        public string UseFlag { get; set; }
        public string HAdminID { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public bool RememberMe { get; internal set; }
        public string RegisterFailMessage { get; internal set; }
        public string LoginErrorMessage { get; internal set; }
    }
}
